apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: project-name
  labels:
    app: project-name
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: project-name
        tier: app
    spec:
      containers:
      - name: project-name
        image: gcr.io/${project}/project-name:${cluster}
        imagePullPolicy: Always
