apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: projectName
  labels:
    app: projectName
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: projectName
        tier: app
    spec:
      containers:
      - name: projectName
        image: gcr.io/${project}/projectName
        imagePullPolicy: Always
        env:
        - name: PSQL_URL
          valueFrom:
            secretKeyRef:
              name: ${cluster}-projectName
              key: PSQL_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: ${cluster}-projectName
              key: REDIS_URL
