export const projectTypes = {
  "Browser/Client Package": [
    "babel",
    "babel-scripts",
    "babel-web",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-scripts",
    "watchman-babel",
  ],
  "Lerna Monorepo": ["babel", "eslint", "husky", "lerna"],
  "Next Package": [
    "babel",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "next",
  ],
  "React Native Web Package": [
    "babel",
    "babel-scripts",
    "babel-web-react",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "react-native-web",
    "watchman-babel",
  ],
  "React Package": [
    "babel",
    "babel-scripts",
    "babel-web-react",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "watchman-babel",
  ],
  "Sass Package": ["sass", "watchman-sass"],
  "Server/Task Package": [
    "babel",
    "babel-node",
    "babel-scripts",
    "eslint",
    "husky",
    "jest",
    "jest-node",
    "jest-scripts",
    "watchman-babel",
  ],
}
