export const projectTypes = {
  "Browser/client package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-scripts",
    "watchman-babel",
  ],
  "Dot-event operation package": [
    "basics",
    "babel",
    "babel-node",
    "babel-scripts",
    "dot-event",
    "eslint",
    "husky",
    "jest",
    "jest-node",
    "jest-scripts",
    "watchman-babel",
  ],
  "Kubernetes redis": ["kubes-redis"],
  "Kubernetes service": ["kubes-service"],
  "Lerna monorepo": [
    "basics",
    "babel",
    "eslint",
    "husky",
    "lerna",
  ],
  "Next package": [
    "basics",
    "babel",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "next",
  ],
  "React Native Web package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web-react",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "react-native-web",
    "watchman-babel",
  ],
  "React package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web-react",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "watchman-babel",
  ],
  "Sass package": ["basics", "sass", "watchman-sass"],
  "Server/task package": [
    "basics",
    "babel",
    "babel-node",
    "babel-scripts",
    "eslint",
    "husky",
    "jest",
    "jest-node",
    "jest-scripts",
    "watchman-babel",
  ],
}
