export const projectTypes = {
  "Babel package": [
    "basics",
    "babel",
    "babel-node",
    "babel-scripts",
    "eslint",
    "eslint-es6",
    "husky",
    "jest",
    "jest-babel",
    "jest-node",
    "jest-scripts",
    "watchman-babel",
  ],
  "Browser Babel package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web",
    "eslint",
    "eslint-es6",
    "husky",
    "jest",
    "jest-babel",
    "jest-browser",
    "jest-scripts",
    "watchman-babel",
  ],
  "Dot-event composer": [
    "basics",
    "babel",
    "babel-node",
    "babel-scripts",
    "dot-event",
    "eslint",
    "eslint-es6",
    "husky",
    "jest",
    "jest-babel",
    "jest-node",
    "jest-scripts",
    "watchman-babel",
  ],
  "ES6 package": [
    "basics",
    "eslint",
    "husky",
    "jest",
    "jest-node",
    "jest-scripts",
    "watchman-babel",
  ],
  "Kubernetes redis": ["kubes-redis"],
  "Kubernetes service": ["kubes-service"],
  "Next package": [
    "basics",
    "babel",
    "eslint",
    "eslint-es6",
    "eslint-react",
    "husky",
    "jest",
    "jest-babel",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "next",
  ],
  "React Native Web package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web-react",
    "eslint",
    "eslint-es6",
    "eslint-react",
    "husky",
    "jest",
    "jest-babel",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "react-native-web",
    "watchman-babel",
  ],
  "React package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web-react",
    "eslint",
    "eslint-es6",
    "eslint-react",
    "husky",
    "jest",
    "jest-babel",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "watchman-babel",
  ],
  "Sass package": ["basics", "sass", "watchman-sass"],
}
