export const projectTypes = {
  "Browser/Client Package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-scripts",
    "watchman-babel",
  ],
  "Dot-event Operation Package": [
    "basics",
    "babel",
    "babel-node",
    "babel-scripts",
    "dot-event",
    "eslint",
    "husky",
    "jest",
    "jest-node",
    "jest-scripts",
    "watchman-babel",
  ],
  "Kubernetes Service": ["kubes-service"],
  "Lerna Monorepo": [
    "basics",
    "babel",
    "eslint",
    "husky",
    "lerna",
  ],
  "Next Package": [
    "basics",
    "babel",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "next",
  ],
  "React Native Web Package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web-react",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "react-native-web",
    "watchman-babel",
  ],
  "React Package": [
    "basics",
    "babel",
    "babel-scripts",
    "babel-web-react",
    "eslint",
    "husky",
    "jest",
    "jest-browser",
    "jest-react",
    "jest-scripts",
    "watchman-babel",
  ],
  "Sass Package": ["basics", "sass", "watchman-sass"],
  "Server/Task Package": [
    "basics",
    "babel",
    "babel-node",
    "babel-scripts",
    "eslint",
    "husky",
    "jest",
    "jest-node",
    "jest-scripts",
    "watchman-babel",
  ],
}
