apiVersion: v1
kind: Service
metadata:
  name: project-name-redis
  labels:
    app: project-name-redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: project-name-redis
    role: master
    tier: backend
